---
# tasks file for ansible-proxmox-provision

- block:
  - name: Provision
    proxmox:
      vmid: "{{hostvars[item]['inventory_hostname_short'] | regex_replace('[A-Za-z-_.]', '')}}"
      state: present
      node: "{{proxmox_node}}"
      api_user: "{{proxmox_api_user}}"
      api_password: "{{proxmox_api_password}}"
      api_host: "{{proxmox_api_host}}"
      password: "{{ proxmox_provision_password }}"
      ostemplate: "{{proxmox_provision_api_storage}}/{{ proxmox_provision_template_file }}"
      hostname: "{{item}}"
      memory: "{{ proxmox_provision_memory }}"
      netif: "{{proxmox_provision_netif}}"
    register: pct_config_01
    with_items: "{{proxmox_provision_hosts}}"
    delegate_to: localhost

  - name: Start the container
    proxmox:
      state: started
      vmid: "{{hostvars[item]['inventory_hostname_short'] | regex_replace('[A-Za-z-_.]', '')}}"
      api_user: "{{proxmox_api_user}}"
      api_password: "{{proxmox_api_password}}"
      api_host: "{{proxmox_api_host}}"
    with_items: "{{proxmox_provision_hosts}}"
    delegate_to: localhost

  - set_fact:
      proxmox_provision_created: true
    when: pct_config_01.changed

  when: "{{proxmox_regex_hostname}}"

- block:
  - name: Provision
    proxmox:
      vmid: "{{hostvars[item]['pve_id']}}"
      state: present
      node: "{{proxmox_node}}"
      api_user: "{{proxmox_api_user}}"
      api_password: "{{proxmox_api_password}}"
      api_host: "{{proxmox_api_host}}"
      password: "{{ proxmox_provision_password }}"
      ostemplate: "{{proxmox_provision_api_storage}}/{{ proxmox_provision_template_file }}"
      hostname: "{{item}}"
      memory: "{{ proxmox_provision_memory }}"
      netif: "{{proxmox_provision_netif}}"
    register: pct_config_01
    with_items: "{{proxmox_provision_hosts}}"
    delegate_to: localhost

  - name: Start the container
    proxmox:
      state: started
      vmid: "{{hostvars[item]['pve_id']}}"
      api_user: "{{proxmox_api_user}}"
      api_password: "{{proxmox_api_password}}"
      api_host: "{{proxmox_api_host}}"
    with_items: "{{proxmox_provision_hosts}}"
    delegate_to: localhost

  - set_fact:
      proxmox_provision_created: true
    when: pct_config_01.changed

  when: not "{{proxmox_regex_hostname}}"


